#!/bin/sh

setup_emacs() {
    git clone --recursive https://github.com/arnm/emacs.d ~/.emacs.d
    ~/.emacs.d/setup
}

setup_dots() {

    rm -rf ~/.oh-my-fish

    curl -L https://github.com/bpinto/oh-my-fish/raw/master/tools/install.fish | fish
    curl https://raw.githubusercontent.com/Alex7Kom/nvm-fish/master/install.fish | fish


    rm -rf ~/.i3
    rm -rf ~/.config/fish

    local dot=~/bootstrap/dotfiles

    ln -sf $dot/Xdefaults ~/.Xdefaults
    ln -sf $dot/tmux.conf ~/.tmux.conf
    ln -sf $dot/zshrc ~/.zshrc
    ln -sf $dot/i3 ~/.i3
    ln -sf $dot/config/fish ~/.config/fish
}

setup_dots



