# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="arnm"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=13

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git tmux node npm pip bower autojump zsh-syntax-highlighting mvn nyan)

# User functions

function cjava () {
export JAVA_HOME=$(/usr/libexec/java_home -v $1)
}

function applePressAndHold () {
defaults write -g ApplePressAndHoldEnabled -bool $1
}

# User configuration
source $ZSH/oh-my-zsh.sh
source $HOME/.nvm/nvm.sh
export VIRTUAL_ENV_DISABLE_PROMPT=1
source /usr/local/bin/virtualenvwrapper.sh
export WORKON_HOME=$HOME/.virtualenvs

# source $HOME/bootstrap/dotfiles/zsh/bvrc.sh

export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/core_perl:/bin:/sbin

# supress pip errors
export CFLAGS=-Qunused-arguments
export CPPFLAGS=-Qunused-arguments

alias c="cd"
alias cl="clear"
alias rd="rm -rf"
alias md="mkdir -p"

alias g="git"
alias e="emacs -nw"
alias t="tree"
alias v="vim"

alias ev="vim ~/.vim/vimrc"
alias et="vim ~/.tmux.conf"
alias ex="vim ~/.Xdefaults"
alias ez="vim ~/.zshrc"

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/base16-tomorrow.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# automatically attach/start a tmux session
if [[ $TMUX == "" ]]; then
  tmux attach || tmux new -s sesh
fi

# load up default npm version
if [[ $(nvm_ls_current) == none ]]; then
  nvm use 0.10 > /dev/null
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # faster key repeat
  applePressAndHold false
  # increase limit of open file descriptors
  ulimit -n 2560
elif [[ "$OSTYPE" == "cygwin" ]]; then
elif [[ "$OSTYPE" == "msys" ]]; then
elif [[ "$OSTYPE" == "win32" ]]; then
else
fi

# Add GHC 7.8.4 to the PATH, via https://ghcformacosx.github.io/
export GHC_DOT_APP="/Applications/ghc-7.8.4.app"
if [ -d "$GHC_DOT_APP" ]; then
  export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi

workon default-2.7
cjava 1.7
eval "$(rbenv init -)"


